[build.environment]
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/api"
  to = "https://test.xxchat.chat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
